// <auto-generated />
using System;
using CreditoFiscal.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditoFiscal.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(CreditoFiscalDbContext))]
    partial class CreditoFiscalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditoFiscal.Dominio.Entidades.Credito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("aliquota");

                    b.Property<decimal>("BaseCalculo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_calculo");

                    b.Property<DateTime>("DataConstituicao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_constituicao");

                    b.Property<string>("NumeroCredito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_credito");

                    b.Property<string>("NumeroNfse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_nfse");

                    b.Property<bool>("SimplesNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("simples_nacional");

                    b.Property<string>("TipoCredito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_credito");

                    b.Property<decimal>("ValorDeducao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_deducao");

                    b.Property<decimal>("ValorFaturado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_faturado");

                    b.Property<decimal>("ValorIssqn")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_issqn");

                    b.HasKey("Id");

                    b.HasIndex("NumeroCredito")
                        .IsUnique()
                        .HasDatabaseName("ix_credito_numero_credito");

                    b.HasIndex("NumeroNfse")
                        .HasDatabaseName("ix_credito_numero_nfse");

                    b.ToTable("credito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
